membersrvc:
  image: hyperledger/fabric-membersrvc
  ports:
    - "7054:7054"
  expose:
    - "7054"
  command: membersrvc
vp0:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7053:7053"
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp0
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  links:
  - membersrvc
  expose:
    - "7050"
    - "7051"
    - "7053"
  command: sh -c "until nc -zv membersrvc 7054; do echo 'Waiting for membersrvc to start.'; sleep 5; done; peer node start --peer-chaincodedev"

# simplesample:
#   image: test02
#   environment:
#     - CORE_PEER_ADDRESS=vp0:7051
#   links:
#     - vp0
#   command: sh -c 'sleep 20 && cd SimpleSample && ./bin/runChaincode -a vp0:7051'
